name: Update README with Commit Log

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update README with commit log
        run: python update_readme.py

      - name: Check for changes and commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          if [ -n "$(git status --porcelain README.md)" ]; then
            git add README.md
            git commit -m "docs: auto-update commit log [skip ci]"
            git push
            echo "README updated and pushed"
          else
            echo "No changes to README.md"
          fi
